const SUMAR = require('./sumar')
const RESTAR = require('./restar')
const MULTIPLICAR = require('./multiplicar')
const DIVIDIR = require('./dividir')

console.log(SUMAR(4,9))
console.log(RESTAR(6,8))
console.log(MULTIPLICAR(5,7))
console.log(MULTIPLICAR(0,7))
console.log(MULTIPLICAR(5,0))
console.log(DIVIDIR(5,9))
console.log(DIVIDIR(0,9))
console.log(DIVIDIR(5,0))